### ISSUE TITLE
DesTerm128 v3 cannot recognize Swiftlink.

### ISSUE THREAD

**Issue by MaxPlap** [markusC64/1541ultimate2#25]
As reported in this thread: on [Lemon64](https://www.lemon64.com/forum/viewtopic.php?t=74663),
it looks like Desterm128 v3 does not automatically recognize the ACIA emulation of the U2+ with firmware 3.7
Maybe the software uses a non-canon recognition routine.
Works well with CCGMS

**Comment by AlexB7** [comment]
Desterm 3.02 on the 128 does not detect the ACIA / Turbo232 at startup because after a reset of the ACIA, the value returned from the command register is not what it expects.  If I bypass the detection routine then it works as expected.  It works fine with Novaterm and Dialogue 128.

desboot resets the ACIA to defaults using:

lda #$00
sta $de01

and then it reads the command register and compares it to #$e0 (1110 0000):

lda $de02
cmp #$e0

A real Swiftlink/turbo232 (and Vice) returns:

224 = 1110 0000

while the Ultimate returns:

226 = 1110 0010

The default should be that receive interrupts are enabled (xxxx xx0x).

I tried both settings in the firmware (DE00/NMI & DE00/IRQ) and both returned the same results.

**Comment by MaxPlap** [comment]
Sorry for the late answer.
I tried and it seems to work, at startup desterm displayed the first time "Swiftlink 3.6MHz @ DE00", then "Swiftlink 1.8MHz @ DE00" and the third time "CMD Turbo232 @ DE00".
I tried multiple times after that, but it still shows "CMD Turbo232 @ DE00". I don't know what happened and what may cause that different recognition.
Anyway, the emulation works flawlessly. Closing.
